server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RosemaryHan/springcloud-config.git
          #uri:git@github:com:zzyybs/springcloud-config:git: 这种类型地址没用
          search-paths:
            - springcloud-config
      label: master
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"