server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystri-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可显示IP
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1